tasks, schedule static, analysis

diff --git a/PL/scripts/enp b/PL/scripts/enp
--- a/PL/scripts/enp
+++ b/PL/scripts/enp
@@ -1,10 +1,7 @@
 #!/bin/bash
-# Este script ejecuta el fichero introducido como argumento a través de la "ColaGPU"
-# A continuación, imprime el resultado del fichero con el nombre resultante "<argumento>.o<numId>"
-# Finalmente, elimina el fichero resultante.
 
-if [ ! $# -eq 1 ]; then
-    echo "USO: enp <fichero>"
+if [ $# -eq 0 -o $# -ge 3 ]; then
+    echo "USO: enp <fichero> [cola]"
     exit 1
 fi
 
@@ -13,15 +10,65 @@ if [ ! -s $1 ]; then
     exit 1
 fi
 
-ColaGPU $1
-echo "Esperando..."
+# array con los nombres de las colas:
+cola[0]="i3"
+cola[1]="xeon"
+cola[2]="gpu"
 
-while [ $(qstat | wc -l) -gt 2 ]; do
-    sleep 2
+# Comprobar que el segundo argumento es el nombre de una cola si existe.
+# Si no se han introducido dos argumentos, utilizar la cola "gpu".
+# Guardar el valor del índice del array en la variable "index".
+if [ $# -eq 2 ]; then
+    index=0
+    for i in ${cola[*]}; do
+        if [ $i == $2 ]; then
+            break
+        fi
+        index=$(($index+1))
+    done
+    if [ $index -eq 3 ]; then
+        echo "ERROR: La cola $2 no existe."
+        exit 1
+    fi
+else
+    index=2
+fi
+
+# Ejecutar el fichero en la cola correspondiente.
+# Para ejecutar en la cola "gpu", se utilza el comando "ColaGPU $1".
+# Para ejecutar en las colas "i3" y "xeon", se utiliza el comando "ColaI3 $1" y "ColaXeon $1" respectivamente.
+# Guardar el mensaje de ejecución en la variable "msg".
+if [ $index -eq 2 ]; then
+    msg=$(ColaGPU $1)
+else
+    if [ $index -eq 0 ]; then
+        msg=$(ColaI3 $1)
+    else
+        msg=$(ColaXeon $1)
+    fi
+fi
+
+
+id=$(echo $msg | cut -d' ' -f3) # Obtener el número del trabajo del mensaje de ejecución.
+echo "enp: $id esperando en cola ${cola[$index]} ($(date +%T))" # Imprimir el nombre de la cola y el número del trabajo.
+
+# obtener trabajos por delante del nuestro en la cola
+# si no hay ninguno, el valor de "trabajos" será 0
+trabajos=$(qstat | grep ${cola[$index]} | grep -B 1000000 $id | wc -l)
+
+# Imprimir un mensaje cuando el trabajo entre en la cola.
+# Un trabajo está en la cola si tiene la flag "r" en la columna "state" de "qstat".
+while [ $(qstat | grep $id | cut -d' ' -f7 | grep qw | wc -l) -eq 1 ]; do
+    sleep 1
 done
+echo "enp: $id está ejecutando ($(date +%T))"
+while [ $(qstat | grep $id | wc -l) -eq 1 ]; do
+    sleep 1
+done
+echo "enp: $id ha terminado ($(date +%T))"
 
-cat $1.o*
-rm $1.o*
+cat $1.o$id
+rm $1.o$id
 
 if [ -f core.* ]; then
     rm core.*
